### ISSUE TITLE
Нужно больше примеров в Гите

### ISSUE THREAD

**Issue by ghost** [raul1798/Python_programs#1]
Приветствую!
Твой Гит не плох , но не дотягивает до того , что бы по нему можно было сказать : "Я хочу что бы он работал на меня"

Возможно стоит добавить немного больше кода?

С Уважением к Тебе , Осипов Пётр .

**Comment by raul1798** [comment]
Привет, спасибо за отзыв, что бы вы мне посоветовали?

. 

  02.07.2016, 20:16:23 пользователь smartwebdever (notifications@github.com)
  написал:

  Приветствую!
  Твой Гит не плох , но не дотягивает до того , что бы по нему можно было
  сказать : "Я хочу что бы он работал на меня"

  Возможно стоит добавить немного больше кода?

  С Уважением к Тебе , Осипов Пётр .

**Comment by ghost** [comment]
по больше кода , хоть и for-fun-only , но он должен быть более практичным , что-ли
Более подходящим под практическое применение

напиши одну программу под лицензией GPL3.0 , и дай её людям
Было бы замечательно
Это повысит твои шансы в сотни раз

**Comment by ghost** [comment]
В целом , это все пожелания тебе на текущий момент . Удачи в постижении Питона
